load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")

# gazelle:prefix github.com/andyscott/gazelle_policy
gazelle_binary(
    name = "gazelle_policy",
    languages = [
        "//language/policy",
        "@gazelle//language/go",
    ],
    visibility = ["//visibility:public"],
)

gazelle(
    name = "gazelle",
    command = "fix",
    gazelle = ":gazelle_policy",
)

gazelle(
    name = "gazelle_ci",
    command = "fix",
    extra_args = ["-mode=diff"],
    gazelle = ":gazelle_policy",
)
