# Cut a release whenever a semantic-version tag is pushed.
name: Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      publish_token:
        required: true
  push:
    tags:
      - "v*.*.*"

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.4.0
    with:
      release_files: gazelle_fold-*.tar.gz
      prerelease: false
      tag_name: ${{ inputs.tag_name || github.ref_name }}

  publish:
    needs: release
    uses: ./.github/workflows/publish.yaml
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
    secrets:
      publish_token: ${{ secrets.publish_token || secrets.BCR_PUBLISH_TOKEN }}
